### ISSUE TITLE
Error when execute MAKE

### ISSUE THREAD

**Issue by mak0275** [Maroc-OS/CleanedBitCrack#10]
In file included from clContext.h:4:0,
                 from clContext.cpp:4:
clUtil.h:20:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
In file included from clerrors.cpp:1:0:
clUtil.h:20:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
In file included from clUtil.cpp:1:0:
clUtil.h:20:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:6: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/mnt/f/cleanedbitcrack/clUtil'
Makefile:138: recipe for target 'dir_clutil' failed
make: *** [dir_clutil] Error 2

can someone help please.....

**Comment by Maroc-OS** [comment]
try using #include <CL/cl.hpp> instead

**Comment by Maroc-OS** [comment]
fixed on #ef35aa5
