### ISSUE TITLE
random not work

### ISSUE THREAD

**Issue by Noname400** [Maroc-OS/CleanedBitCrack#12]
cuBitCrack.exe -b 16 -t 128 -p 256 -i 1to32.txt -o f.txt -r --compression both

**Comment by Maroc-OS** [comment]
What is the output. And notice that there is no `-o` option with `-r`

Try `-h` to see arg description.

On Fri, 16 Jul 2021 at 1:56 PM, Noname400 ***@***.***> wrote:

> cuBitCrack.exe -b 16 -t 128 -p 256 -i 1to32.txt -o f.txt -r --compression
> both
> .
>
-- 
-- 
-----------------------------------------
Merruk Technology, SARL.
www.merruk.com

**Comment by Noname400** [comment]
I'm sorry, but I don't understand you.
how do i enable random mode?

**Comment by Maroc-OS** [comment]
-r switch

xxBitCrack -r

I'm sorry, but I don't understand you.
> how do i enable random mode?
>
-- 
-- 
-----------------------------------------
Merruk Technology, SARL.
www.merruk.com
