### ISSUE TITLE
error

### ISSUE THREAD

**Issue by drk77** [Maroc-OS/CleanedBitCrack#7]
I can’t create a build on ubuntu - it gives an error
CudaAtomicList.h:6:10: fatal error: sys/_types/_null.h: File not found
 #include <sys/_types/_null.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Maroc-OS** [comment]
Confirmed for CUDA.

OS Compatibility issue. this was used here for macOS.

can you remove that line and try recompile safely. or change this :

```
#if defined(__APPLE__) || defined(__linux__) || defined(__CYGWIN__)
#include <sys/_types/_null.h>
#endif
```

with this :

```
#if defined(__APPLE__)
#include <sys/_types/_null.h>
#elif defined(__linux__) || defined(__CYGWIN__)
#include <sys/types.h>
#endif
```

give me back .
