### ISSUE TITLE
error with make and Kan not start it 

### ISSUE THREAD

**Issue by olieter** [Maroc-OS/CleanedBitCrack#9]
the start when I command  make 
........done
.........done
.......at last
duplicate symbol '__bitcrack_cl' in:
    bitcrack_cl.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libCLKeySearchDevice.a] Error 1
make: *** [dir_clKeySearchDevice] Error 2

when I start it    mypc  CleanedBitCrack-master % clBitCrack 1FshYsUh3mqgsG29XpZ23eLjWV8Ur3VwH
zsh: command not found: clBitCrack

how most I start it?

**Comment by Maroc-OS** [comment]
do ```make clean``` before you make again and try latest code
